//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dorokhov.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accounting
    {
        public int IdAccounting { get; set; }
        public int IdEmployee { get; set; }
        public string CodeEquipment { get; set; }
        public string NumberOfRoom { get; set; }
        public System.DateTime DateOfRegistration { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Equipment Equipment { get; set; }
        public virtual Room Room { get; set; }
    }
}
